# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

environment-aliases:
  - &env-defaults
    AWS_PAGER: ""

executors:
  circleci-nextgen-node-10:
    docker:
      # - image: cimg/node:10.22
      - image: cimg/base:2020.01
    # working_directory: /mnt/ramdisk
    working_directory: /home/circleci/project
    environment: *env-defaults

defaults: &defaults
  executor: circleci-nextgen-node-10

commands:
  custom_workspace_save:
    description: "Must be followed by CircleCI workspace persist. Save a custom workspace tar, allowing exclusion. Exclude must be a comma separated list of quoted paths/segments to pass to tar"
    parameters:
      exclude:
        type: string
      paths:
        type: string
    steps:
      - run:
          name: Create tarball
          command: |
            custom_workspace_workdir=/home/circleci/custom_workspace
            excludesFile=${custom_workspace_workdir}/exclusions.txt
            includesFile=${custom_workspace_workdir}/inclusions.txt

            mkdir "$custom_workspace_workdir"
            printf '<< parameters.paths >>' awk -F"," '{for(i=1;i<=NF;i++){print $i}}' > "$includesFile"
            printf '<< parameters.exclude >>' awk -F"," '{for(i=1;i<=NF;i++){print $i}}' > "$excludesFile"
            echo includesFile:
            cat "$includesFile"
            echo excludesFile:
            cat "$excludesFile"
            tar -cvf ${custom_workspace_workdir}/workspace.tar --files-from="$includesFile"
            echo 'export custom_workspace_workdir=$custom_workspace_workdir' >> $BASH_ENV
      - persist_to_workspace:
          root: /home/circleci/custom_workspace
          paths:
            - "*"
  custom_workspace_restore:
    description: "Restore a custom workspace. must be preceded by CircleCI workspace attach"
    parameters:
      at:
        type: string
        default: "./"
    steps:
      - attach_workspace:
          at: /home/circleci/custom_workspace
      - run:
          name: Restore tarball
          command: |
            custom_workspace_workdir=/home/circleci/custom_workspace
            tar -xvf ${custom_workspace_workdir}/workspace.tar -C << parameters.at >>
jobs:
  script1:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Copy File
          command: |
            cp test.txt test2.txt
      - custom_workspace_save:
          exclude: "*exclude*,*donot*"
          paths: "./"
  script2:
    <<: *defaults
    steps:
      - custom_workspace_restore
      - run:
          name: List files
          command: |
            ls -lahR *
      - run:
          name: Read File
          command: |
            cat test2.txt

workflows:
  welcome:
    jobs:
      - script1
      - script2:
          requires:
            - script1
