# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

environment-aliases:
  - &env-defaults
    AWS_PAGER: ""

executors:
  circleci-nextgen-node-10:
    docker:
      # - image: cimg/node:10.22
      - image: cimg/base:2020.01
    # working_directory: /mnt/ramdisk
    working_directory: /home/circleci/project
    environment: *env-defaults

defaults: &defaults
  executor: circleci-nextgen-node-10

commands:
  custom_workspace_save:
    description: "Save a custom workspace tar, allowing exclusion. Exclude must be a comma separated list of quoted paths/segments to pass to tar"
    parameters:
      exclude:
        type: string
        default: "/dev/null"
      paths:
        type: string
      tag:
        type: string
        default: "0"
    steps:
      - run:
          name: Create tarball
          command: |
            custom_workspace_workdir=/home/circleci/custom_workspace
            excludesFile=${custom_workspace_workdir}/exclusions-<< parameters.tag >>.txt
            includesFile=${custom_workspace_workdir}/inclusions-<< parameters.tag >>.txt

            IFS=', ' read -r -a inclusions \<<< "<< parameters.paths >>"
            for included in "${inclusions[@]}"; do
                echo "Including paths:"
                echo "$included" | tee >> "$includesFile"
            done
            IFS=', ' read -r -a exclusions \<<< "<< parameters.exclude >>"
            for excluded in "${exclusions[@]}"; do
                echo "Including paths:"
                echo "$excluded" | tee >> "$excludesFile"
            done

            GZIP=--fast tar -czvf ${custom_workspace_workdir}/workspace-<< parameters.tag >>.tar.gz --exclude-from="$excludesFile" --files-from="$includesFile" | tee > /tmp/workspace-<< parameters.tag >>-files.txt
            echo 'export custom_workspace_workdir=$custom_workspace_workdir' >> $BASH_ENV
      - persist_to_workspace:
          root: /home/circleci/custom_workspace
          paths:
            - "*"
      - store_artifacts:
          path: /home/circleci/custom_workspace/exclusions-<< parameters.tag >>.txt
      - store_artifacts:
          path: /home/circleci/custom_workspace/inclusions-<< parameters.tag >>.txt
      - store_artifacts:
          path: /tmp/workspace-<< parameters.tag >>-files.txt
  custom_workspace_restore:
    description: "Restore a custom workspace. Specify the directory to restore to using the at parameter"
    parameters:
      at:
        type: string
        default: "./"
      tag:
        type: string
        default: "0"
    steps:
      - attach_workspace:
          at: /home/circleci/custom_workspace
      - run:
          name: Restore tarball
          command: |
            custom_workspace_workdir=/home/circleci/custom_workspace
            tar -xzf ${custom_workspace_workdir}/workspace-<< parameters.tag >>.tar.gz -C << parameters.at >>
jobs:
  script1:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Copy File
          command: |
            cp test.txt test2.txt
      - custom_workspace_save:
          exclude: "*exclude*,*donot*"
          paths: "./"
  script2:
    <<: *defaults
    steps:
      - custom_workspace_restore
      - run:
          name: List files
          command: |
            ls -lahR *
      - run:
          name: Read File
          command: |
            cat test2.txt
      # - run:
      #     name: Test exclusions
      #     command: |
      #       if

workflows:
  welcome:
    jobs:
      - script1
      - script2:
          requires:
            - script1
